POST http://localhost:8081/api/v1/ddl/table/queuedCreate

{
    "spaces": {
        "adb__adg_test__env_test_actual": {
            "format": [
                {
                    "name": "id",
                    "type": "integer",
                    "is_nullable": false
                },
                {
                    "name": "bucket_id",
                    "type": "unsigned",
                    "is_nullable": false
                },
                {
                    "name": "sys_from",
                    "type": "number",
                    "is_nullable": false
                },
                {
                    "name": "sys_to",
                    "type": "number",
                    "is_nullable": true
                },
                {
                    "name": "sys_op",
                    "type": "number",
                    "is_nullable": false
                },
                {
                    "name": "gos_number",
                    "type": "string",
                    "is_nullable": true
                }
            ],
            "temporary": false,
            "engine": "vinyl",
            "indexes": [
                {
                    "unique": true,
                    "parts": [
                        {
                            "path": "id",
                            "type": "integer",
                            "is_nullable": false
                        },
                        {
                            "path": "sys_from",
                            "type": "number",
                            "is_nullable": false
                        }
                    ],
                    "type": "TREE",
                    "name": "id"
                },
                {
                    "unique": false,
                    "parts": [
                        {
                            "path": "sys_from",
                            "type": "number",
                            "is_nullable": false
                        }
                    ],
                    "type": "TREE",
                    "name": "x_sys_from"
                },
                {
                    "unique": false,
                    "parts": [
                        {
                            "path": "bucket_id",
                            "type": "unsigned",
                            "is_nullable": false
                        }
                    ],
                    "type": "TREE",
                    "name": "bucket_id"
                }
            ],
            "is_local": false,
            "sharding_key": [
                "id"
            ]
        },
        "adb__adg_test__env_test_history": {
            "format": [
                {
                    "name": "id",
                    "type": "integer",
                    "is_nullable": false
                },
                {
                    "name": "bucket_id",
                    "type": "unsigned",
                    "is_nullable": false
                },
                {
                    "name": "sys_from",
                    "type": "number",
                    "is_nullable": false
                },
                {
                    "name": "sys_to",
                    "type": "number",
                    "is_nullable": true
                },
                {
                    "name": "sys_op",
                    "type": "number",
                    "is_nullable": false
                },
                {
                    "name": "gos_number",
                    "type": "string",
                    "is_nullable": true
                }
            ],
            "temporary": false,
            "engine": "vinyl",
            "indexes": [
                {
                    "unique": true,
                    "parts": [
                        {
                            "path": "id",
                            "type": "integer",
                            "is_nullable": false
                        },
                        {
                            "path": "sys_from",
                            "type": "number",
                            "is_nullable": false
                        }
                    ],
                    "type": "TREE",
                    "name": "id"
                },
                {
                    "unique": false,
                    "parts": [
                        {
                            "path": "sys_from",
                            "type": "number",
                            "is_nullable": false
                        }
                    ],
                    "type": "TREE",
                    "name": "x_sys_from"
                },
                {
                    "unique": false,
                    "parts": [
                        {
                            "path": "sys_to",
                            "type": "number",
                            "is_nullable": true
                        },
                        {
                            "path": "sys_op",
                            "type": "number",
                            "is_nullable": false
                        }
                    ],
                    "type": "TREE",
                    "name": "x_sys_to"
                },
                {
                    "unique": false,
                    "parts": [
                        {
                            "path": "bucket_id",
                            "type": "unsigned",
                            "is_nullable": false
                        }
                    ],
                    "type": "TREE",
                    "name": "bucket_id"
                }
            ],
            "is_local": false,
            "sharding_key": [
                "id"
            ]
        },
        "adb__adg_test__env_test_staging": {
            "format": [
                {
                    "name": "id",
                    "type": "integer",
                    "is_nullable": false
                },
                {
                    "name": "gos_number",
                    "type": "string",
                    "is_nullable": true
                },
                {
                    "name": "sys_op",
                    "type": "number",
                    "is_nullable": false
                },
                {
                    "name": "bucket_id",
                    "type": "unsigned",
                    "is_nullable": false
                }
            ],
            "temporary": false,
            "engine": "vinyl",
            "indexes": [
                {
                    "unique": true,
                    "parts": [
                        {
                            "path": "id",
                            "type": "integer",
                            "is_nullable": false
                        }
                    ],
                    "type": "TREE",
                    "name": "id"
                },
                {
                    "unique": false,
                    "parts": [
                        {
                            "path": "bucket_id",
                            "type": "unsigned",
                            "is_nullable": false
                        }
                    ],
                    "type": "TREE",
                    "name": "bucket_id"
                }
            ],
            "is_local": false,
            "sharding_key": [
                "id"
            ]
        }
    }
}
###

GET http://localhost:8081/api/etl/transfer_data_to_scd_table?_stage_data_table_name=adb__adg_test__env_test_staging&_actual_data_table_name=adb__adg_test__env_test_actual&_historical_data_table_name=adb__adg_test__env_test_history&_delta_number=100

###

POST http://localhost:8081/api/v1/ddl/table/schema

{"spaces":["adb__adg_test__env_test_actual","adb__adg_test__env_test_actual","adb__adg_test__env_test_staging"]}

###

# возможно вызывать с callback чтобы сразу запустить загрузку данных через /kafka/subscription:
# example 3 в спецификации opeapi 
POST http://localhost:8081/api/v1/kafka/subscription

{
  "topicName": "TEST",
  "consumerGroupName": "tarantool",
  "spaceNames": ["adb__adg_test__env_test_staging"],
  "maxNumberOfMessagesPerPartition": 100
}

###

POST http://localhost:8081/api/v1/kafka/dataload

{"topicName":"test","spaces":["env_test_staging"]}

###

DELETE  http://localhost:8081/api/v1/ddl/table/queuedDelete

{"tableList":["adb__adg_test__env_test_actual","adb__adg_test__env_test_actual","adb__adg_test__env_test_staging"]}

###

]